lambda:
  region: "us-east-1"
  function: "pro-streaming-ws-messagesender"

dynamodb:
  region: "us-east-1"
  users-table: "streaming-users-online"
  servers-table: "chat-servers"
  chat-config-table: "streaming-dispatcher-config"

http:
  host: ":8888"
